@ECHO OFF
REM Auto-generated by libinteractive. Do not edit.

REM Compile all programs
call compile.bat
IF ERRORLEVEL 1 EXIT /B !ERRORLEVEL!

REM Run the driver
libinteractive\run.exe %*
IF ERRORLEVEL 1 EXIT /B !ERRORLEVEL!
