version: 2
jobs:
  build:
    working_directory: ~/Curso-OMI
    docker:
      - image: circleci/python:3.5
    steps:
      - checkout
      - run:
          command: |
            cd utils
            sudo pip install pipenv
            pipenv install
      - run: cd utils && pipenv run python3 generateouts.py
      - run: cd utils && pipenv run python3 runtests.py
      - add_ssh_keys
      - deploy:
          name: Deploy to public branch
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              cd utils
              pipenv run python3 upload.py || exit 1
              chmod +x publish && ./publish || exit 1
            fi
workflows:
  version: 2
  test-and-publish:
    jobs:
      - build:
          filters:
            branches:
              ignore: public
