alias: COMI-Veredictos

admin-groups: [Workshop-2017]

generate-output: false

params:
  title: Introducción a omegaUp
  source: Curso OMI

  visibility: 1

  languages: none

  time_limit: 1000
  memory_limit: 32768
  output_limit: 16384
  stack_limit: 10485760

  overall_wall_time_limit: 60000

  # valid options: token-caseless, token-numeric, token-numeric, custom, literal
  validator: token-caseless
  validator_time_limit: 1000
  extra_wall_time: 0

  email_clarifications: 0
