interface Main {
	
	int guardar(
		int indice
	);

	int obtener(
		int indice
	);	

	bool desplazar(
		int indice
	);
	
	void insertar(
		int indice
	);
};

interface InsertionSortInteractivo {
	
	void ordenar(
		int n
	);

};

